SELECT
    E.IDEMPRESA,
    E.IDPRODUTO,
    E.IDSUBPRODUTO,
    SUM(E.QTDATUALESTOQUE) / 1000.0 AS QTDESTOQUE
FROM DBA.ESTOQUE_SALDO_ATUAL E
WHERE E.IDEMPRESA IN (1, 3)
GROUP BY E.IDEMPRESA, E.IDPRODUTO, E.IDSUBPRODUTO
FOR READ ONLY;
