-- TUBOS E CONEXÕES - últimos 3 meses automaticamente

-- CTE: Vendas detalhadas
WITH VendasBrutasPeriodoDetalhe AS (
    SELECT
        EA.DTMOVIMENTO,
        EA.IDVENDEDOR,
        CF.NOME AS NomeVendedor,

        CASE
            WHEN OI.TIPOMOVIMENTO = 'E' THEN EA.VALTOTLIQUIDO * -1
            ELSE EA.VALTOTLIQUIDO
        END AS VALOR_LIQUIDO,

        CASE
            WHEN LEFT(COALESCE(P.DESCRCOMPRODUTO, '') || ' ' || COALESCE(PG.SUBDESCRICAO, ''), 4) = 'TUBO'
                 AND (COALESCE(P.DESCRCOMPRODUTO, '') || ' ' || COALESCE(PG.SUBDESCRICAO, '')) NOT LIKE '%EXTENS.%'
            THEN 'Tubo'

            WHEN LEFT(COALESCE(P.DESCRCOMPRODUTO, '') || ' ' || COALESCE(PG.SUBDESCRICAO, ''), 4) <> 'TUBO'
                 AND (COALESCE(P.DESCRCOMPRODUTO, '') || ' ' || COALESCE(PG.SUBDESCRICAO, '')) NOT LIKE '%EXTENS.%'
                 AND (COALESCE(P.DESCRCOMPRODUTO, '') || COALESCE(PG.SUBDESCRICAO, '')) NOT LIKE '%ADESIVO%'
                 AND (COALESCE(P.DESCRCOMPRODUTO, '') || COALESCE(PG.SUBDESCRICAO, '')) NOT LIKE '%BOIA%'
                 AND (COALESCE(P.DESCRCOMPRODUTO, '') || COALESCE(PG.SUBDESCRICAO, '')) NOT LIKE '%FITA%'
                 AND (COALESCE(P.DESCRCOMPRODUTO, '') || COALESCE(PG.SUBDESCRICAO, '')) NOT LIKE '%4X2%'
                 AND (COALESCE(P.DESCRCOMPRODUTO, '') || COALESCE(PG.SUBDESCRICAO, '')) NOT LIKE '%VEDACAO%'
                 AND (COALESCE(P.DESCRCOMPRODUTO, '') || COALESCE(PG.SUBDESCRICAO, '')) NOT LIKE '%CAIXA%'
                 AND (COALESCE(P.DESCRCOMPRODUTO, '') || COALESCE(PG.SUBDESCRICAO, '')) NOT LIKE '%ESFE%'
                 AND (COALESCE(P.DESCRCOMPRODUTO, '') || COALESCE(PG.SUBDESCRICAO, '')) NOT LIKE '%LAVAT.%'
                 AND (COALESCE(P.DESCRCOMPRODUTO, '') || COALESCE(PG.SUBDESCRICAO, '')) NOT LIKE '%ELETROD.%'
                 AND (COALESCE(P.DESCRCOMPRODUTO, '') || COALESCE(PG.SUBDESCRICAO, '')) NOT LIKE '%QUADRO%'
                 AND (COALESCE(P.DESCRCOMPRODUTO, '') || COALESCE(PG.SUBDESCRICAO, '')) NOT LIKE '%VALVULA%'
                 AND (COALESCE(P.DESCRCOMPRODUTO, '') || COALESCE(PG.SUBDESCRICAO, '')) NOT LIKE '%ENGATE%'
                 AND (COALESCE(P.DESCRCOMPRODUTO, '') || COALESCE(PG.SUBDESCRICAO, '')) NOT LIKE '%TAMPA%'
                 AND (COALESCE(P.DESCRCOMPRODUTO, '') || COALESCE(PG.SUBDESCRICAO, '')) NOT LIKE '%TORN.%'
                 AND (COALESCE(P.DESCRCOMPRODUTO, '') || COALESCE(PG.SUBDESCRICAO, '')) NOT LIKE '%FIXACAO%'
                 AND (COALESCE(P.DESCRCOMPRODUTO, '') || COALESCE(PG.SUBDESCRICAO, '')) NOT LIKE '%RALO%'
                 AND (COALESCE(P.DESCRCOMPRODUTO, '') || COALESCE(PG.SUBDESCRICAO, '')) NOT LIKE '%GRELHA%'
                 AND (COALESCE(P.DESCRCOMPRODUTO, '') || COALESCE(PG.SUBDESCRICAO, '')) NOT LIKE '%TELHA%'
                 AND (COALESCE(P.DESCRCOMPRODUTO, '') || COALESCE(PG.SUBDESCRICAO, '')) NOT LIKE '%CUMEEIRA%'
            THEN 'Conexão'

            ELSE 'Outros'
        END AS TipoProduto

    FROM
        DBA.ESTOQUE_ANALITICO EA
    INNER JOIN DBA.PRODUTO P
        ON EA.IDPRODUTO = P.IDPRODUTO
    INNER JOIN DBA.PRODUTO_GRADE PG
        ON P.IDPRODUTO = PG.IDPRODUTO AND EA.IDSUBPRODUTO = PG.IDSUBPRODUTO
    INNER JOIN DBA.OPERACAO_INTERNA OI
        ON EA.IDOPERACAO = OI.IDOPERACAO
    LEFT JOIN DBA.CLIENTE_FORNECEDOR CF
        ON EA.IDVENDEDOR = CF.IDCLIFOR
    WHERE
        P.FABRICANTE IN ('AMANCO', 'PLASTUBOS', 'KRONA', 'PRECON')
        AND OI.TIPOMOVIMENTO IN ('V', 'E')
        AND EA.DTMOVIMENTO BETWEEN DATE(SUBSTR(CHAR(CURRENT DATE - 3 MONTHS), 1, 7) || '-01') AND CURRENT DATE
        AND EA.IDEMPRESA IN (1, 3)
        AND EA.IDVENDEDOR IS NOT NULL
        AND EA.IDVENDEDOR > 0
)

-- Consulta Final
SELECT
    DTMOVIMENTO,
    IDVENDEDOR,
    NomeVendedor,
    VALOR_LIQUIDO,
    TipoProduto
FROM
    VendasBrutasPeriodoDetalhe
WHERE
    TipoProduto IN ('Tubo', 'Conexão');
