-- SQL REVISADO PARA BUSCAR PRODUTOS ELIT E AMANCO
-- Mantendo a estrutura solicitada de agrupamento para campanhas
WITH DEVOLUCOES_CACHE AS (
    SELECT
        ND.IDEMPRESA,
        ND.IDPLANILHA,
        ND.NUMSEQUENCIADEVOLUCAO,
        ND.IDPRODUTO,
        ND.IDSUBPRODUTO
    FROM
        DBA.NOTAS_DEVOLUCAO ND
    JOIN DBA.DEVOLUCAO_LOGISTICA_MOVIMENTO DLM
        ON  DLM.IDEMPRESA = ND.IDEMPRESA
        AND DLM.IDPLANILHA = ND.IDPLANILHA
        AND DLM.NUMSEQUENCIADEV = ND.NUMSEQUENCIADEVOLUCAO
        AND DLM.IDPRODUTO = ND.IDPRODUTO
        AND DLM.IDSUBPRODUTO = ND.IDSUBPRODUTO
    WHERE
        DLM.FLAGGERARREENTREGA = 'T'
)
SELECT
    EA.DTMOVIMENTO,
    EA.IDVENDEDOR AS IDVENDEDOR,
    COALESCE(V.NOME, 'SEM VENDEDOR') AS NOMEVENDEDOR,
    EA.IDPRODUTO,
    EA.IDSUBPRODUTO,
    -- Concatena o nome do produto com a descrição da grade
    (P.DESCRCOMPRODUTO || ' ' || PG.SUBDESCRICAO) AS DESCRICAO_PRODUTO,
    CASE 
        WHEN P.IDMARCAFABRICANTE = 30 THEN 'AMANCO'
        WHEN P.IDMARCAFABRICANTE = 1129 THEN 'ELIT'
        ELSE P.FABRICANTE 
    END AS FABRICANTE,
    -- Soma as quantidades, ignorando devoluções de reentrega
    SUM(
        CASE 
            WHEN OI.TIPOMOVIMENTO = 'E' AND NOT EXISTS (
                SELECT 1
                FROM DEVOLUCOES_CACHE DC
                WHERE DC.IDEMPRESA = EA.IDEMPRESA
                  AND DC.IDPLANILHA = EA.IDPLANILHA
                  AND DC.NUMSEQUENCIADEVOLUCAO = EA.NUMSEQUENCIA
                  AND DC.IDPRODUTO = EA.IDPRODUTO
                  AND DC.IDSUBPRODUTO = EA.IDSUBPRODUTO
            ) THEN -ABS(EA.QTDPRODUTO)
            WHEN OI.TIPOMOVIMENTO = 'E' THEN 0
            ELSE ABS(EA.QTDPRODUTO)
        END
    ) AS QTD,
    -- Soma os valores, ignorando devoluções de reentrega
    SUM(
        CASE 
            WHEN OI.TIPOMOVIMENTO = 'E' AND NOT EXISTS (
                SELECT 1
                FROM DEVOLUCOES_CACHE DC
                WHERE DC.IDEMPRESA = EA.IDEMPRESA
                  AND DC.IDPLANILHA = EA.IDPLANILHA
                  AND DC.NUMSEQUENCIADEVOLUCAO = EA.NUMSEQUENCIA
                  AND DC.IDPRODUTO = EA.IDPRODUTO
                  AND DC.IDSUBPRODUTO = EA.IDSUBPRODUTO
            ) THEN -ABS(EA.VALTOTLIQUIDO)
            WHEN OI.TIPOMOVIMENTO = 'E' THEN 0
            ELSE ABS(EA.VALTOTLIQUIDO)
        END
    ) AS VALOR_LIQUIDO
FROM
    DBA.ESTOQUE_ANALITICO EA
    JOIN DBA.OPERACAO_INTERNA OI ON OI.IDOPERACAO = EA.IDOPERACAO
    JOIN DBA.PRODUTO_GRADE PG ON PG.IDPRODUTO = EA.IDPRODUTO
    AND PG.IDSUBPRODUTO = EA.IDSUBPRODUTO
    JOIN DBA.PRODUTO P ON P.IDPRODUTO = EA.IDPRODUTO
    LEFT JOIN DBA.CLIENTE_FORNECEDOR V ON V.IDCLIFOR = EA.IDVENDEDOR
    JOIN DBA.NOTAS_ENTRADA_SAIDA NES ON NES.IDEMPRESA = EA.IDEMPRESA
    AND NES.IDPLANILHA = EA.IDPLANILHA
    AND NES.IDOPERACAO = EA.IDOPERACAO
    AND NES.DTMOVIMENTO = EA.DTMOVIMENTO
    JOIN DBA.NOTAS N ON N.IDEMPRESA = NES.IDEMPRESA
    AND N.IDPLANILHA = NES.IDPLANILHA
WHERE
    EA.IDEMPRESA IN (1, 2, 3)
    AND EA.IDOPERACAO <> 1301
    AND OI.FLAGMOVPRODUTOS = 'T'
    AND OI.TIPOMOVIMENTO IN ('V', 'E')
    AND COALESCE(EA.NUMSEQUENCIAKIT, 0) <= 0
    AND N.FLAGNOTACANCEL = 'F'
    AND NES.TIPOITEMCATEGORIA NOT IN ('D5', 'D8')
    -- ✅ FILTRANDO APENAS ELIT (1129) E AMANCO (30)
    AND P.IDMARCAFABRICANTE IN (30, 1129)
    -- ✅ PERÍODO DINÂMICO PASSADO PELO PYTHON
    AND EA.DTMOVIMENTO BETWEEN {{d '{data_inicio}'}} AND {{d '{data_fim}'}}
GROUP BY
    EA.DTMOVIMENTO,
    EA.IDVENDEDOR,
    V.NOME,
    EA.IDPRODUTO,
    EA.IDSUBPRODUTO,
    P.DESCRCOMPRODUTO,
    PG.SUBDESCRICAO,
    CASE WHEN P.IDMARCAFABRICANTE = 30 THEN 'AMANCO' WHEN P.IDMARCAFABRICANTE = 1129 THEN 'ELIT' ELSE P.FABRICANTE END FOR READ ONLY;