-- VENDAS E DEVOLUÇÃO - últimos 3 meses apenas dos vendedores específicos

-- Parâmetros
WITH PARAMETROS (DATA_INICIO, DATA_FIM) AS (
    VALUES (
        DATE(SUBSTR(CHAR(CURRENT DATE - 3 MONTHS), 1, 7) || '-01'),
        CURRENT DATE
    )
),

-- Empresas válidas
EMPRESAS (IDEMPRESA) AS (
    VALUES (1), (3)
),

-- Vendedores específicos
VENDEDORES (IDCLIFOR) AS (
    VALUES 
        (13656), (1000024), (1005676), (1006781), 
        (1011021), (1000023), (1000020), (1013676)
),

-- Cache de reentrega
DEVOLUCOES_CACHE AS (
    SELECT
        ND.IDEMPRESA,
        ND.IDPLANILHA,
        ND.NUMSEQUENCIADEVOLUCAO,
        ND.IDPRODUTO,
        ND.IDSUBPRODUTO
    FROM
        DBA.NOTAS_DEVOLUCAO ND
    JOIN DBA.DEVOLUCAO_LOGISTICA_MOVIMENTO DLM
        ON  DLM.IDEMPRESA = ND.IDEMPRESA
        AND DLM.IDPLANILHA = ND.IDPLANILHA
        AND DLM.NUMSEQUENCIADEV = ND.NUMSEQUENCIADEVOLUCAO
        AND DLM.IDPRODUTO = ND.IDPRODUTO
        AND DLM.IDSUBPRODUTO = ND.IDSUBPRODUTO
    WHERE
        DLM.FLAGGERARREENTREGA = 'T'
)

-- Consulta final
SELECT
    EA.IDVENDEDOR,
    CF.NOME AS NOME_VENDEDOR,
    EA.IDPLANILHA,
    EA.IDSUBPRODUTO,
    EA.VALTOTLIQUIDO,
    EA.DTMOVIMENTO,
    NES.IDCLIFORENTREGA,
    OP.TIPOMOVIMENTO,
    CONFIG.TIPOMOVIMENTO AS CONFIG_TIPOMOV,
    EA.IDOPERACAO,

    CASE
        WHEN OP.TIPOMOVIMENTO = 'V'
             OR (EA.IDOPERACAO = 3000 AND CONFIG.TIPOMOVIMENTO = 'V')
        THEN 1 ELSE 0
    END AS IS_VENDA,

    CASE
        WHEN OP.TIPOMOVIMENTO = 'E' THEN 1 ELSE 0
    END AS IS_DEVOLUCAO,

    CASE
        WHEN OP.TIPOMOVIMENTO = 'E'
            AND NOT EXISTS (
                SELECT 1
                FROM DEVOLUCOES_CACHE DC
                WHERE DC.IDEMPRESA = EA.IDEMPRESA
                  AND DC.IDPLANILHA = EA.IDPLANILHA
                  AND DC.NUMSEQUENCIADEVOLUCAO = EA.NUMSEQUENCIA
                  AND DC.IDPRODUTO = EA.IDPRODUTO
                  AND DC.IDSUBPRODUTO = EA.IDSUBPRODUTO
            )
        THEN 1 ELSE 0
    END AS IS_DEVOLUCAO_REAL

FROM
    DBA.ESTOQUE_ANALITICO EA
JOIN EMPRESAS E ON EA.IDEMPRESA = E.IDEMPRESA
JOIN PARAMETROS P ON EA.DTMOVIMENTO BETWEEN P.DATA_INICIO AND P.DATA_FIM
JOIN DBA.NOTAS N ON N.IDEMPRESA = EA.IDEMPRESA AND N.IDPLANILHA = EA.IDPLANILHA
JOIN DBA.NOTAS_ENTRADA_SAIDA NES ON NES.IDEMPRESA = N.IDEMPRESA AND NES.IDPLANILHA = N.IDPLANILHA
JOIN DBA.OPERACAO_INTERNA OP ON OP.IDOPERACAO = NES.IDOPERACAO
JOIN DBA.OPERACAO_INTERNA CONFIG ON CONFIG.IDOPERACAO = 3000
LEFT JOIN DBA.CLIENTE_FORNECEDOR CF ON CF.IDCLIFOR = EA.IDVENDEDOR
JOIN VENDEDORES V ON V.IDCLIFOR = EA.IDVENDEDOR

WHERE
    EA.IDOPERACAO != 1301
    AND OP.FLAGMOVPRODUTOS = 'T'
    AND EA.IDVENDEDOR > 0;
