SELECT NOTA.DTMOVIMENTO,
NOTA.IDCLIFOR,
NOTA.IDEMPRESA,
NOTA.NOME,
NOTA.NUMNOTA,
NOTA.SERIENOTA,
CAST(SUM( NOTA.VALCONTABIL ) AS NUMERIC(30,6)) AS VALCONTABIL,
CAST(SUM( NOTA.LUCRO ) AS NUMERIC(30,6)) AS LUCRO
FROM (SELECT NOTAS.DTMOVIMENTO,
NOTAS.IDCLIFOR,
NOTAS.IDEMPRESA,
CASE OPERACAO_INTERNA.TIPOMOVIMENTO
WHEN 'E' THEN
CLIENTE_FORNECEDOR.NOME || '-DEV'
ELSE
CLIENTE_FORNECEDOR.NOME
END AS NOME,
CASE
WHEN NOTAS.SERIENOTA LIKE 'EC%' OR NOTAS.SERIENOTA = 'CFE' THEN
NOTAS.NUMCUPOMFISCAL
WHEN NOTAS.SERIENOTA LIKE 'PDV%' THEN
(SELECT ORCAMENTO_PRE_NOTA.IDORCAMENTO FROM ORCAMENTO_PRE_NOTA
WHERE IDPLANILHAPRENOTA = NOTAS.IDPLANILHA)
ELSE
NOTAS.NUMNOTA
END AS NUMNOTA,
NOTAS.SERIENOTA,
CASE OPERACAO_INTERNA.TIPOMOVIMENTO
WHEN 'E' THEN
SUM ( ESTOQUE_ANALITICO.VALTOTLIQUIDO ) * -1
ELSE
SUM ( ESTOQUE_ANALITICO.VALTOTLIQUIDO )
END AS VALCONTABIL,
CASE WHEN ESTOQUE_ANALITICO.TIPOBAIXAMESTRE = 'K' THEN
(SELECT
CASE OPERACAO_INTERNA.TIPOMOVIMENTO WHEN 'E' THEN
SUM( COALESCE( EST.VALLUCRO, 0 ) * EST.QTDPRODUTO ) * -1
ELSE
SUM( COALESCE( EST.VALLUCRO, 0 ) * EST.QTDPRODUTO )
END
FROM
ESTOQUE_ANALITICO AS EST
WHERE
COALESCE(EST.NUMSEQUENCIAKIT,0) = ESTOQUE_ANALITICO.NUMSEQUENCIA AND
EST.IDPLANILHA = ESTOQUE_ANALITICO.IDPLANILHA AND
EST.IDSUBPRODUTO IN (
(
SELECT
PRODKIT.IDSUBPRODUTO
FROM
PRODUTO_KIT AS PRODKIT
WHERE
PRODKIT.IDPRODUTOKIT = ESTOQUE_ANALITICO.IDPRODUTO AND
PRODKIT.IDSUBPRODUTOKIT = ESTOQUE_ANALITICO.IDSUBPRODUTO
))
)
ELSE
CASE OPERACAO_INTERNA.TIPOMOVIMENTO
WHEN 'E' THEN
SUM( COALESCE( (ESTOQUE_ANALITICO.VALLUCRO*ESTOQUE_ANALITICO.QTDPRODUTO), 0 )) * -1
ELSE
SUM( COALESCE( (ESTOQUE_ANALITICO.VALLUCRO*ESTOQUE_ANALITICO.QTDPRODUTO), 0 ) )
END
END AS LUCRO
FROM NOTAS,
CLIENTE_FORNECEDOR,
NOTAS_ENTRADA_SAIDA,
OPERACAO_INTERNA,
OPERACAO_INTERNA AS CONFIG,
(ESTOQUE_ANALITICO LEFT OUTER JOIN CLIENTE_FORNECEDOR AS VENDEDOR ON
ESTOQUE_ANALITICO.IDVENDEDOR = VENDEDOR.IDCLIFOR),
PRODUTO_GRADE
WHERE NOTAS.IDCLIFOR = CLIENTE_FORNECEDOR.IDCLIFOR AND
CONFIG.IDOPERACAO = 3000 AND
ESTOQUE_ANALITICO.IDEMPRESA = NOTAS.IDEMPRESA AND
ESTOQUE_ANALITICO.IDPLANILHA = NOTAS.IDPLANILHA AND
NOTAS_ENTRADA_SAIDA.IDEMPRESA = NOTAS.IDEMPRESA AND
NOTAS_ENTRADA_SAIDA.IDPLANILHA = NOTAS.IDPLANILHA AND
NOTAS_ENTRADA_SAIDA.IDOPERACAO = ESTOQUE_ANALITICO.IDOPERACAO AND
NOTAS_ENTRADA_SAIDA.TIPOITEMCATEGORIA NOT IN('D8') AND
ESTOQUE_ANALITICO.IDOPERACAO <> 1301 AND PRODUTO_GRADE.IDPRODUTO = ESTOQUE_ANALITICO.IDPRODUTO AND
PRODUTO_GRADE.IDSUBPRODUTO = ESTOQUE_ANALITICO.IDSUBPRODUTO AND
OPERACAO_INTERNA.FLAGMOVPRODUTOS = 'T' AND	( ( ESTOQUE_ANALITICO.NUMSEQUENCIAKIT IS NULL ) OR ( ESTOQUE_ANALITICO.NUMSEQUENCIAKIT <= 0 ) ) AND
OPERACAO_INTERNA.IDOPERACAO = NOTAS_ENTRADA_SAIDA.IDOPERACAO AND
( OPERACAO_INTERNA.TIPOMOVIMENTO IN ( 'V', 'E' ) ) AND
NOTAS.FLAGNOTACANCEL = 'F' AND
ESTOQUE_ANALITICO.DTMOVIMENTO BETWEEN {d '2026-03-01' } AND {d '2026-03-31' } AND
(NOTAS.SERIENOTA <> 'CAN' OR (NOTAS.SERIENOTA = 'CAN' AND CONFIG.TIPOMOVIMENTO = 'V')) AND
NOTAS.IDEMPRESA IN ( 1,2,3 ) AND
(SELECT
COUNT(0)
FROM
NOTAS_DEVOLUCAO,
DEVOLUCAO_LOGISTICA_MOVIMENTO,
NOTAS_ENTRADA_SAIDA AS ORIGEM_DEVOLUCAO
WHERE
NOTAS_DEVOLUCAO.IDEMPRESA = ESTOQUE_ANALITICO.IDEMPRESA AND
NOTAS_DEVOLUCAO.IDPLANILHA = ESTOQUE_ANALITICO.IDPLANILHA AND
NOTAS_DEVOLUCAO.NUMSEQUENCIADEVOLUCAO = ESTOQUE_ANALITICO.NUMSEQUENCIA AND
NOTAS_DEVOLUCAO.IDPRODUTO = ESTOQUE_ANALITICO.IDPRODUTO AND
NOTAS_DEVOLUCAO.IDSUBPRODUTO = ESTOQUE_ANALITICO.IDSUBPRODUTO AND
ORIGEM_DEVOLUCAO.IDEMPRESA = NOTAS_DEVOLUCAO.IDEMPRESA AND
ORIGEM_DEVOLUCAO.IDPLANILHA = NOTAS_DEVOLUCAO.IDPLANILHADEVOLUCAO AND
DEVOLUCAO_LOGISTICA_MOVIMENTO.IDEMPRESA = NOTAS_DEVOLUCAO.IDEMPRESA AND
DEVOLUCAO_LOGISTICA_MOVIMENTO.IDPLANILHA = NOTAS_DEVOLUCAO.IDPLANILHA AND
DEVOLUCAO_LOGISTICA_MOVIMENTO.NUMSEQUENCIADEV = NOTAS_DEVOLUCAO.NUMSEQUENCIADEVOLUCAO AND
DEVOLUCAO_LOGISTICA_MOVIMENTO.IDPRODUTO = NOTAS_DEVOLUCAO.IDPRODUTO AND
DEVOLUCAO_LOGISTICA_MOVIMENTO.IDSUBPRODUTO = NOTAS_DEVOLUCAO.IDSUBPRODUTO AND
DEVOLUCAO_LOGISTICA_MOVIMENTO.FLAGGERARREENTREGA = 'T') = 0
AND NOT EXISTS (SELECT 1
FROM ORCAMENTO_PRE_NOTA OPN INNER JOIN ORCAMENTO_PROD_NOTA_ANTECIPADA OPNA ON OPNA.IDEMPRESAORCAMENTO = OPN.IDEMPRESAORCAMENTO AND OPNA.IDORCAMENTO = OPN.IDORCAMENTO
LEFT JOIN ESTOQUE_ANALITICO EA ON OPN.IDEMPRESAPRENOTA = EA.IDEMPRESA
AND OPN.IDPLANILHAPRENOTA = EA.IDPLANILHA LEFT JOIN ESTOQUE_ANALITICO EA2 ON OPNA.IDEMPRESANOTA = EA2.IDEMPRESA
AND OPNA.IDPLANILHANOTA = EA2.IDPLANILHA LEFT JOIN OPERACAO_INTERNA OP ON OP.IDOPERACAO = EA.IDOPERACAO
LEFT JOIN OPERACAO_INTERNA OP2 ON OP2.IDOPERACAO = EA2.IDOPERACAO	WHERE OPN.IDPLANILHAPRENOTA = NOTAS_ENTRADA_SAIDA.IDPLANILHA
AND OP.TIPOMOVIMENTO = 'V'
AND OP2.TIPOMOVIMENTO = 'V'
FETCH FIRST 1 ROWS ONLY) AND vendedor.idclifor in( 10774) GROUP BY NOTAS.IDCLIFOR,
NOTAS.IDPLANILHA,
CLIENTE_FORNECEDOR.NOME,
OPERACAO_INTERNA.TIPOMOVIMENTO,
NUMCUPOMFISCAL,
NUMNOTA,
SERIENOTA,
NOTAS.IDEMPRESA,
NOTAS.DTMOVIMENTO,
ESTOQUE_ANALITICO.IDPLANILHA,
ESTOQUE_ANALITICO.IDPRODUTO,
ESTOQUE_ANALITICO.IDSUBPRODUTO,
ESTOQUE_ANALITICO.TIPOBAIXAMESTRE,
ESTOQUE_ANALITICO.NUMSEQUENCIA
UNION ALL
SELECT NOTAS.DTMOVIMENTO,
NOTAS.IDCLIFOR,
NOTAS.IDEMPRESA,
CASE OPERACAO_INTERNA.TIPOMOVIMENTO
WHEN 'E' THEN
CLIENTE_FORNECEDOR.NOME || '-DEV(Reentrega)'
ELSE
CLIENTE_FORNECEDOR.NOME
END AS NOME,
CASE
WHEN NOTAS.SERIENOTA LIKE 'EC%' OR NOTAS.SERIENOTA = 'CFE' THEN
NOTAS.NUMCUPOMFISCAL
WHEN NOTAS.SERIENOTA LIKE 'PDV%' THEN
(SELECT ORCAMENTO_PRE_NOTA.IDORCAMENTO FROM ORCAMENTO_PRE_NOTA
WHERE IDPLANILHAPRENOTA = NOTAS.IDPLANILHA)
ELSE
NOTAS.NUMNOTA
END AS NUMNOTA,
NOTAS.SERIENOTA,
CASE OPERACAO_INTERNA.TIPOMOVIMENTO
WHEN 'E' THEN
SUM ( ESTOQUE_ANALITICO.VALTOTLIQUIDO ) * -1
ELSE
SUM ( ESTOQUE_ANALITICO.VALTOTLIQUIDO )
END AS VALCONTABIL,
CASE WHEN ESTOQUE_ANALITICO.TIPOBAIXAMESTRE = 'K' THEN
(SELECT
CASE OPERACAO_INTERNA.TIPOMOVIMENTO WHEN 'E' THEN
SUM( COALESCE( EST.VALLUCRO, 0 ) * EST.QTDPRODUTO ) * -1
ELSE
SUM( COALESCE( EST.VALLUCRO, 0 ) * EST.QTDPRODUTO )
END
FROM
ESTOQUE_ANALITICO AS EST
WHERE
COALESCE(EST.NUMSEQUENCIAKIT,0) = ESTOQUE_ANALITICO.NUMSEQUENCIA AND
EST.IDPLANILHA = ESTOQUE_ANALITICO.IDPLANILHA AND
EST.IDSUBPRODUTO IN (
(
SELECT
PRODKIT.IDSUBPRODUTO
FROM
PRODUTO_KIT AS PRODKIT
WHERE
PRODKIT.IDPRODUTOKIT = ESTOQUE_ANALITICO.IDPRODUTO AND
PRODKIT.IDSUBPRODUTOKIT = ESTOQUE_ANALITICO.IDSUBPRODUTO
))
)
ELSE
CASE OPERACAO_INTERNA.TIPOMOVIMENTO
WHEN 'E' THEN
SUM( COALESCE( (ESTOQUE_ANALITICO.VALLUCRO*ESTOQUE_ANALITICO.QTDPRODUTO), 0 )) * -1
ELSE
SUM( COALESCE( (ESTOQUE_ANALITICO.VALLUCRO*ESTOQUE_ANALITICO.QTDPRODUTO), 0 ) )
END
END AS LUCRO
FROM NOTAS,
CLIENTE_FORNECEDOR,
NOTAS_ENTRADA_SAIDA,
OPERACAO_INTERNA,
(ESTOQUE_ANALITICO LEFT OUTER JOIN CLIENTE_FORNECEDOR AS VENDEDOR ON
ESTOQUE_ANALITICO.IDVENDEDOR = VENDEDOR.IDCLIFOR),
PRODUTO_GRADE
WHERE NOTAS.IDCLIFOR = CLIENTE_FORNECEDOR.IDCLIFOR AND
ESTOQUE_ANALITICO.IDEMPRESA = NOTAS.IDEMPRESA AND
ESTOQUE_ANALITICO.IDPLANILHA = NOTAS.IDPLANILHA AND
NOTAS_ENTRADA_SAIDA.IDEMPRESA = NOTAS.IDEMPRESA AND
NOTAS_ENTRADA_SAIDA.IDPLANILHA = NOTAS.IDPLANILHA AND
NOTAS_ENTRADA_SAIDA.IDOPERACAO = ESTOQUE_ANALITICO.IDOPERACAO AND
NOTAS_ENTRADA_SAIDA.TIPOITEMCATEGORIA NOT IN('D8') AND
ESTOQUE_ANALITICO.IDOPERACAO <> 1301 AND PRODUTO_GRADE.IDPRODUTO = ESTOQUE_ANALITICO.IDPRODUTO AND
PRODUTO_GRADE.IDSUBPRODUTO = ESTOQUE_ANALITICO.IDSUBPRODUTO AND
OPERACAO_INTERNA.FLAGMOVPRODUTOS = 'T' AND
( ( ESTOQUE_ANALITICO.NUMSEQUENCIAKIT IS NULL ) OR ( ESTOQUE_ANALITICO.NUMSEQUENCIAKIT <= 0 ) ) AND
OPERACAO_INTERNA.IDOPERACAO = NOTAS_ENTRADA_SAIDA.IDOPERACAO AND
( OPERACAO_INTERNA.TIPOMOVIMENTO = 'E' ) AND
NOTAS.FLAGNOTACANCEL = 'F' AND
ESTOQUE_ANALITICO.DTMOVIMENTO BETWEEN {d '2026-03-01' } AND {d '2026-03-31' } AND
NOTAS.IDEMPRESA IN ( 1,2,3 ) AND
(SELECT
COUNT(0)
FROM
NOTAS_DEVOLUCAO,
DEVOLUCAO_LOGISTICA_MOVIMENTO,
NOTAS_ENTRADA_SAIDA AS ORIGEM_DEVOLUCAO,
OPERACAO_INTERNA AS OPERACAO_INTERNA_DEVOLUCAO
WHERE
NOTAS_DEVOLUCAO.IDEMPRESA = ESTOQUE_ANALITICO.IDEMPRESA AND
NOTAS_DEVOLUCAO.IDPLANILHA = ESTOQUE_ANALITICO.IDPLANILHA AND
NOTAS_DEVOLUCAO.NUMSEQUENCIADEVOLUCAO = ESTOQUE_ANALITICO.NUMSEQUENCIA AND
NOTAS_DEVOLUCAO.IDPRODUTO = ESTOQUE_ANALITICO.IDPRODUTO AND
NOTAS_DEVOLUCAO.IDSUBPRODUTO = ESTOQUE_ANALITICO.IDSUBPRODUTO AND
ORIGEM_DEVOLUCAO.IDEMPRESA = NOTAS_DEVOLUCAO.IDEMPRESA AND
ORIGEM_DEVOLUCAO.IDPLANILHA = NOTAS_DEVOLUCAO.IDPLANILHADEVOLUCAO AND
DEVOLUCAO_LOGISTICA_MOVIMENTO.IDEMPRESA = NOTAS_DEVOLUCAO.IDEMPRESA AND
DEVOLUCAO_LOGISTICA_MOVIMENTO.IDPLANILHA = NOTAS_DEVOLUCAO.IDPLANILHA AND
DEVOLUCAO_LOGISTICA_MOVIMENTO.NUMSEQUENCIADEV = NOTAS_DEVOLUCAO.NUMSEQUENCIADEVOLUCAO AND
DEVOLUCAO_LOGISTICA_MOVIMENTO.IDPRODUTO = NOTAS_DEVOLUCAO.IDPRODUTO AND
DEVOLUCAO_LOGISTICA_MOVIMENTO.IDSUBPRODUTO = NOTAS_DEVOLUCAO.IDSUBPRODUTO AND
OPERACAO_INTERNA.TIPOMOVIMENTO = 'E' AND
OPERACAO_INTERNA_DEVOLUCAO.IDOPERACAO = ORIGEM_DEVOLUCAO.IDOPERACAO AND
OPERACAO_INTERNA_DEVOLUCAO.TIPOMOVIMENTO = 'V' AND
ORIGEM_DEVOLUCAO.IDOPERACAO = 3001 AND
DEVOLUCAO_LOGISTICA_MOVIMENTO.FLAGGERARREENTREGA = 'T') > 0
AND vendedor.idclifor in( 10774) GROUP BY NOTAS.IDCLIFOR,
NOTAS.IDPLANILHA,
CLIENTE_FORNECEDOR.NOME,
OPERACAO_INTERNA.TIPOMOVIMENTO,
NUMCUPOMFISCAL,
NUMNOTA,
SERIENOTA,
NOTAS.IDEMPRESA,
NOTAS.DTMOVIMENTO,
ESTOQUE_ANALITICO.IDPLANILHA,
ESTOQUE_ANALITICO.IDPRODUTO,
ESTOQUE_ANALITICO.IDSUBPRODUTO,
ESTOQUE_ANALITICO.TIPOBAIXAMESTRE,
ESTOQUE_ANALITICO.NUMSEQUENCIA
) AS NOTA
GROUP BY NOTA.IDCLIFOR,
NOTA.NOME,
NOTA.NUMNOTA,
NOTA.SERIENOTA,
NOTA.IDEMPRESA,
NOTA.DTMOVIMENTO FOR READ ONLY
