"""
DB2 SQL query strings shared by erp_sync.py and bootstrap_historico.py.

All queries:
  - Use raw ERP tables (no views required in the DB2 schema)
  - Filter WITH UR (uncommitted read) — no shared locks on ERP pages
  - Take exactly two positional parameters: (date_from, date_to) as date objects
  - Assume current schema is already set to DBA on the connection
"""

# ─── Vendas (sales movements) ─────────────────────────────────────────────────
# Columns: IDVENDEDOR, NOME_VENDEDOR, IDEMPRESA, IDPLANILHA, DT_MOVIMENTO, TOTALVENDA_LINHA
SQL_VENDAS = """
SELECT
    CAST(CASE WHEN COALESCE(EA.IDVENDEDOR, 0) = 0 THEN '0'
         ELSE CAST(EA.IDVENDEDOR AS VARCHAR(50)) END AS VARCHAR(50))   AS IDVENDEDOR,
    CAST(CASE WHEN COALESCE(EA.IDVENDEDOR, 0) = 0 THEN '<SEM VENDEDOR>'
         ELSE COALESCE(VEN.NOME, 'DESCONHECIDO') END AS VARCHAR(120))  AS NOME_VENDEDOR,
    CAST(EA.IDEMPRESA AS INTEGER)                                       AS IDEMPRESA,
    CAST(EA.IDPLANILHA AS VARCHAR(50))                                  AS IDPLANILHA,
    DATE(NES.DTMOVIMENTO)                                               AS DT_MOVIMENTO,
    COALESCE(CASE WHEN OI.TIPOMOVIMENTO = 'E'
                  THEN EA.VALTOTLIQUIDO * -1
                  ELSE EA.VALTOTLIQUIDO END, 0)                         AS TOTALVENDA_LINHA
FROM DBA.ESTOQUE_ANALITICO EA
LEFT JOIN DBA.CLIENTE_FORNECEDOR VEN ON VEN.IDCLIFOR = EA.IDVENDEDOR,
     DBA.NOTAS N,
     DBA.NOTAS_ENTRADA_SAIDA NES,
     DBA.OPERACAO_INTERNA OI
WHERE NES.DTMOVIMENTO >= ?
  AND NES.DTMOVIMENTO <= ?
  AND N.IDEMPRESA    = EA.IDEMPRESA  AND N.IDPLANILHA   = EA.IDPLANILHA
  AND NES.IDEMPRESA  = EA.IDEMPRESA  AND NES.IDPLANILHA = EA.IDPLANILHA
  AND NES.IDOPERACAO = EA.IDOPERACAO
  AND OI.IDOPERACAO  = NES.IDOPERACAO
  AND OI.FLAGMOVPRODUTOS = 'T'
  AND OI.TIPOMOVIMENTO IN ('V', 'E')
  AND EA.IDEMPRESA IN (1, 2, 3)
  AND N.FLAGNOTACANCEL = 'F'
  AND EA.IDOPERACAO <> 1301
  AND (EA.NUMSEQUENCIAKIT IS NULL OR EA.NUMSEQUENCIAKIT <= 0)
  AND NES.TIPOITEMCATEGORIA NOT IN ('D5', 'D8')
WITH UR
"""

# ─── Campanhas (product-level sales for campaign calculations) ────────────────
# Columns: IDVENDEDOR, NOMEVENDEDOR, IDPRODUTO, FABRICANTE, VALOR_LIQUIDO, QTD, DTMOVIMENTO
SQL_CAMPANHAS = """
SELECT
    CAST(CASE WHEN COALESCE(EA.IDVENDEDOR, 0) = 0 THEN '0'
         ELSE CAST(EA.IDVENDEDOR AS VARCHAR(50)) END AS VARCHAR(50))   AS IDVENDEDOR,
    CAST(CASE WHEN COALESCE(EA.IDVENDEDOR, 0) = 0 THEN '<SEM VENDEDOR>'
         ELSE COALESCE(VEN.NOME, 'DESCONHECIDO') END AS VARCHAR(120))  AS NOMEVENDEDOR,
    CAST(EA.IDPRODUTO AS VARCHAR(50))                                   AS IDPRODUTO,
    CAST(COALESCE(FAB.NOME, 'SEM FABRICANTE') AS VARCHAR(120))         AS FABRICANTE,
    COALESCE(CASE WHEN OI.TIPOMOVIMENTO = 'E'
                  THEN EA.VALTOTLIQUIDO * -1
                  ELSE EA.VALTOTLIQUIDO END, 0)                         AS VALOR_LIQUIDO,
    COALESCE(CASE WHEN OI.TIPOMOVIMENTO = 'E'
                  THEN EA.QTDPRODUTO * -1
                  ELSE EA.QTDPRODUTO END, 0)                            AS QTD,
    DATE(NES.DTMOVIMENTO)                                               AS DTMOVIMENTO
FROM DBA.ESTOQUE_ANALITICO EA
LEFT JOIN DBA.CLIENTE_FORNECEDOR VEN ON VEN.IDCLIFOR = EA.IDVENDEDOR
LEFT JOIN DBA.PRODUTO            PRD ON PRD.IDPRODUTO = EA.IDPRODUTO
LEFT JOIN DBA.CLIENTE_FORNECEDOR FAB ON FAB.IDCLIFOR  = PRD.IDFABRICANTE,
     DBA.NOTAS N,
     DBA.NOTAS_ENTRADA_SAIDA NES,
     DBA.OPERACAO_INTERNA OI
WHERE NES.DTMOVIMENTO >= ?
  AND NES.DTMOVIMENTO <= ?
  AND N.IDEMPRESA    = EA.IDEMPRESA  AND N.IDPLANILHA   = EA.IDPLANILHA
  AND NES.IDEMPRESA  = EA.IDEMPRESA  AND NES.IDPLANILHA = EA.IDPLANILHA
  AND NES.IDOPERACAO = EA.IDOPERACAO
  AND OI.IDOPERACAO  = NES.IDOPERACAO
  AND OI.FLAGMOVPRODUTOS = 'T'
  AND OI.TIPOMOVIMENTO IN ('V', 'E')
  AND EA.IDEMPRESA IN (1, 2, 3)
  AND N.FLAGNOTACANCEL = 'F'
  AND EA.IDOPERACAO <> 1301
  AND (EA.NUMSEQUENCIAKIT IS NULL OR EA.NUMSEQUENCIAKIT <= 0)
  AND NES.TIPOITEMCATEGORIA NOT IN ('D5', 'D8')
WITH UR
"""

# ─── Tubos & Conexões (filtered subset of vendas by product description) ──────
# Columns: IDVENDEDOR, NOME_VENDEDOR, IDEMPRESA, DT_MOVIMENTO, TOTALVENDA_LINHA
SQL_TUBOS = """
SELECT
    CAST(CASE WHEN COALESCE(EA.IDVENDEDOR, 0) = 0 THEN '0'
         ELSE CAST(EA.IDVENDEDOR AS VARCHAR(50)) END AS VARCHAR(50))   AS IDVENDEDOR,
    CAST(CASE WHEN COALESCE(EA.IDVENDEDOR, 0) = 0 THEN '<SEM VENDEDOR>'
         ELSE COALESCE(VEN.NOME, 'DESCONHECIDO') END AS VARCHAR(120))  AS NOME_VENDEDOR,
    CAST(EA.IDEMPRESA AS INTEGER)                                       AS IDEMPRESA,
    DATE(NES.DTMOVIMENTO)                                               AS DT_MOVIMENTO,
    COALESCE(CASE WHEN OI.TIPOMOVIMENTO = 'E'
                  THEN EA.VALTOTLIQUIDO * -1
                  ELSE EA.VALTOTLIQUIDO END, 0)                         AS TOTALVENDA_LINHA
FROM DBA.ESTOQUE_ANALITICO EA
LEFT JOIN DBA.CLIENTE_FORNECEDOR VEN ON VEN.IDCLIFOR = EA.IDVENDEDOR
LEFT JOIN DBA.PRODUTO            PRD ON PRD.IDPRODUTO = EA.IDPRODUTO,
     DBA.NOTAS N,
     DBA.NOTAS_ENTRADA_SAIDA NES,
     DBA.OPERACAO_INTERNA OI
WHERE NES.DTMOVIMENTO >= ?
  AND NES.DTMOVIMENTO <= ?
  AND N.IDEMPRESA    = EA.IDEMPRESA  AND N.IDPLANILHA   = EA.IDPLANILHA
  AND NES.IDEMPRESA  = EA.IDEMPRESA  AND NES.IDPLANILHA = EA.IDPLANILHA
  AND NES.IDOPERACAO = EA.IDOPERACAO
  AND OI.IDOPERACAO  = NES.IDOPERACAO
  AND OI.FLAGMOVPRODUTOS = 'T'
  AND OI.TIPOMOVIMENTO IN ('V', 'E')
  AND EA.IDEMPRESA IN (1, 2, 3)
  AND N.FLAGNOTACANCEL = 'F'
  AND EA.IDOPERACAO <> 1301
  AND (EA.NUMSEQUENCIAKIT IS NULL OR EA.NUMSEQUENCIAKIT <= 0)
  AND NES.TIPOITEMCATEGORIA NOT IN ('D5', 'D8')
  AND (
        UPPER(COALESCE(PRD.DESCRCOMPRODUTO, '')) LIKE '%TUBO%'
     OR UPPER(COALESCE(PRD.DESCRCOMPRODUTO, '')) LIKE '%CONEX%'
  )
WITH UR
"""

# ─── Pendentes (open orders — full-replace strategy, aggregated per vendor) ───
# Columns: NOME_VENDEDOR, IDEMPRESA, TOTALVENDA_LINHA
# Uses TIPOMOVIMENTO = 'P' (pedido/order) — not yet invoiced.
SQL_PENDENTES = """
SELECT
    CAST(CASE WHEN COALESCE(EA.IDVENDEDOR, 0) = 0 THEN '<SEM VENDEDOR>'
         ELSE COALESCE(VEN.NOME, 'DESCONHECIDO') END AS VARCHAR(120))  AS NOME_VENDEDOR,
    CAST(EA.IDEMPRESA AS INTEGER)                                       AS IDEMPRESA,
    COALESCE(SUM(
        CASE WHEN OI.TIPOMOVIMENTO = 'E'
             THEN EA.VALTOTLIQUIDO * -1
             ELSE EA.VALTOTLIQUIDO END
    ), 0)                                                               AS TOTALVENDA_LINHA
FROM DBA.ESTOQUE_ANALITICO EA
LEFT JOIN DBA.CLIENTE_FORNECEDOR VEN ON VEN.IDCLIFOR = EA.IDVENDEDOR,
     DBA.NOTAS N,
     DBA.NOTAS_ENTRADA_SAIDA NES,
     DBA.OPERACAO_INTERNA OI
WHERE NES.DTMOVIMENTO >= ?
  AND NES.DTMOVIMENTO <= ?
  AND N.IDEMPRESA    = EA.IDEMPRESA  AND N.IDPLANILHA   = EA.IDPLANILHA
  AND NES.IDEMPRESA  = EA.IDEMPRESA  AND NES.IDPLANILHA = EA.IDPLANILHA
  AND NES.IDOPERACAO = EA.IDOPERACAO
  AND OI.IDOPERACAO  = NES.IDOPERACAO
  AND OI.FLAGMOVPRODUTOS = 'T'
  AND OI.TIPOMOVIMENTO = 'P'
  AND EA.IDEMPRESA IN (1, 2, 3)
  AND N.FLAGNOTACANCEL = 'F'
  AND (EA.NUMSEQUENCIAKIT IS NULL OR EA.NUMSEQUENCIAKIT <= 0)
GROUP BY VEN.NOME, EA.IDEMPRESA, EA.IDVENDEDOR
WITH UR
"""
