"""
DB2 SQL query strings shared by erp_sync.py and bootstrap_historico.py.

SQL_CONTAS_RECEBER — full snapshot, NO date parameters.
  Reads from CONTAS_RECEBER_SALDOS_VIEW and joins:
    CLIENTE_FORNECEDOR (CF)   → client name, address, salesperson code
    CLIENTE_FORNECEDOR (VEND) → salesperson name
    NOTAS (N)                 → invoice number
    CIDADES_IBGE (CI)         → city/state for billing address
  Filters: VALSALDOTITULO > 0 (only open/partially-open titles)
  Strategy: TRUNCATE + INSERT on every run (full state snapshot).
  Status (VENCIDO/VENCE_HOJE/A_VENCER) computed in Python using dtvencimento vs today.

All queries:
  - Use raw ERP tables (no views required in the DB2 schema)
  - Filter WITH UR (uncommitted read) — no shared locks on ERP pages
  - Most queries take two positional parameters: (date_from, date_to) as date objects
  - SQL_ESTOQUE_SUGESTAO is a snapshot query — takes NO parameters
  - Assume current schema is already set to DBA on the connection

DECIMAL → DOUBLE fix
─────────────────────
DB2's ODBC driver returns DECIMAL(x,6) columns as raw unscaled integers
(e.g. 407703.54 comes back as 407703540000).  Multiplying by 1E0 forces the
expression to DOUBLE, which pyodbc always returns as a Python float with the
decimal point in the correct position.  This is applied to every monetary
column (VALTOTLIQUIDO, VALLUCRO, QTDPRODUTO) across all queries.

NOTAS join fix
──────────────
Replaced INNER JOIN DBA.NOTAS with EXISTS to avoid row-multiplication when
a planilha has multiple NF records (complement notes, partials, etc.).
"""

# ─── Vendas (sales movements) ─────────────────────────────────────────────────
# Columns: IDVENDEDOR, NOME_VENDEDOR, IDEMPRESA, IDPLANILHA, DT_MOVIMENTO, TOTALVENDA_LINHA, IDCLIENTE, NOME_CLIENTE
SQL_VENDAS = """
SELECT
    CAST(CASE WHEN COALESCE(EA.IDVENDEDOR, 0) = 0 THEN '0'
         ELSE CAST(EA.IDVENDEDOR AS VARCHAR(50)) END AS VARCHAR(50))   AS IDVENDEDOR,
    CAST(CASE WHEN COALESCE(EA.IDVENDEDOR, 0) = 0 THEN '<SEM VENDEDOR>'
         ELSE COALESCE(VEN.NOME, 'DESCONHECIDO') END AS VARCHAR(120))  AS NOME_VENDEDOR,
    CAST(EA.IDEMPRESA AS INTEGER)                                       AS IDEMPRESA,
    CAST(EA.IDPLANILHA AS VARCHAR(50))                                  AS IDPLANILHA,
    DATE(NES_H.DTMOVIMENTO)                                             AS DT_MOVIMENTO,
    COALESCE(CASE WHEN OI.TIPOMOVIMENTO = 'E'
                  THEN EA.VALTOTLIQUIDO * -1E0
                  ELSE EA.VALTOTLIQUIDO * 1E0 END, 0E0)                AS TOTALVENDA_LINHA,
    CAST(COALESCE(N.IDCLIFOR, 0) AS VARCHAR(50))                        AS IDCLIENTE,
    CAST(COALESCE(CLI.NOME, '') AS VARCHAR(120))                        AS NOME_CLIENTE
FROM DBA.ESTOQUE_ANALITICO EA
LEFT JOIN DBA.CLIENTE_FORNECEDOR VEN ON VEN.IDCLIFOR = EA.IDVENDEDOR
INNER JOIN (
    SELECT IDEMPRESA, IDPLANILHA, IDOPERACAO,
           MIN(DTMOVIMENTO) AS DTMOVIMENTO
    FROM   DBA.NOTAS_ENTRADA_SAIDA
    WHERE  DTMOVIMENTO >= ?
      AND  DTMOVIMENTO <= ?
      AND  TIPOITEMCATEGORIA NOT IN ('D5', 'D8')
    GROUP BY IDEMPRESA, IDPLANILHA, IDOPERACAO
) NES_H
    ON  NES_H.IDEMPRESA  = EA.IDEMPRESA
    AND NES_H.IDPLANILHA = EA.IDPLANILHA
    AND NES_H.IDOPERACAO = EA.IDOPERACAO
INNER JOIN DBA.OPERACAO_INTERNA OI
    ON  OI.IDOPERACAO      = NES_H.IDOPERACAO
    AND OI.FLAGMOVPRODUTOS = 'T'
    AND OI.TIPOMOVIMENTO   IN ('V', 'E')
INNER JOIN DBA.NOTAS N
    ON  N.IDEMPRESA      = EA.IDEMPRESA
    AND N.IDPLANILHA     = EA.IDPLANILHA
    AND N.FLAGNOTACANCEL = 'F'
LEFT JOIN DBA.CLIENTE_FORNECEDOR CLI ON CLI.IDCLIFOR = N.IDCLIFOR
WHERE EA.IDEMPRESA IN (1, 2, 3)
  AND EA.IDOPERACAO <> 1301
  AND (EA.NUMSEQUENCIAKIT IS NULL OR EA.NUMSEQUENCIAKIT <= 0)
WITH UR
"""

# ─── Campanhas (product-level sales for campaign calculations) ────────────────
# Columns: IDVENDEDOR, NOMEVENDEDOR, IDPRODUTO, FABRICANTE, VALOR_LIQUIDO, QTD, DTMOVIMENTO, IDEMPRESA
SQL_CAMPANHAS = """
SELECT
    CAST(CASE WHEN COALESCE(EA.IDVENDEDOR, 0) = 0 THEN '0'
         ELSE CAST(EA.IDVENDEDOR AS VARCHAR(50)) END AS VARCHAR(50))   AS IDVENDEDOR,
    CAST(CASE WHEN COALESCE(EA.IDVENDEDOR, 0) = 0 THEN '<SEM VENDEDOR>'
         ELSE COALESCE(VEN.NOME, 'DESCONHECIDO') END AS VARCHAR(120))  AS NOMEVENDEDOR,
    CAST(EA.IDPRODUTO AS VARCHAR(50))                                   AS IDPRODUTO,
    CAST(COALESCE(PRD.FABRICANTE, 'SEM FABRICANTE') AS VARCHAR(120))    AS FABRICANTE,
    COALESCE(CASE WHEN OI.TIPOMOVIMENTO = 'E'
                  THEN EA.VALTOTLIQUIDO * -1E0
                  ELSE EA.VALTOTLIQUIDO * 1E0 END, 0E0)                AS VALOR_LIQUIDO,
    COALESCE(CASE WHEN OI.TIPOMOVIMENTO = 'E'
                  THEN EA.QTDPRODUTO * -1E0
                  ELSE EA.QTDPRODUTO * 1E0 END, 0E0)                   AS QTD,
    DATE(NES_H.DTMOVIMENTO)                                             AS DTMOVIMENTO,
    CAST(EA.IDEMPRESA AS VARCHAR(10))                                   AS IDEMPRESA
FROM DBA.ESTOQUE_ANALITICO EA
LEFT JOIN DBA.CLIENTE_FORNECEDOR VEN ON VEN.IDCLIFOR = EA.IDVENDEDOR
LEFT JOIN DBA.PRODUTO            PRD ON PRD.IDPRODUTO = EA.IDPRODUTO
INNER JOIN (
    SELECT IDEMPRESA, IDPLANILHA, IDOPERACAO,
           MIN(DTMOVIMENTO) AS DTMOVIMENTO
    FROM   DBA.NOTAS_ENTRADA_SAIDA
    WHERE  DTMOVIMENTO >= ?
      AND  DTMOVIMENTO <= ?
      AND  TIPOITEMCATEGORIA NOT IN ('D5', 'D8')
    GROUP BY IDEMPRESA, IDPLANILHA, IDOPERACAO
) NES_H
    ON  NES_H.IDEMPRESA  = EA.IDEMPRESA
    AND NES_H.IDPLANILHA = EA.IDPLANILHA
    AND NES_H.IDOPERACAO = EA.IDOPERACAO
INNER JOIN DBA.OPERACAO_INTERNA OI
    ON  OI.IDOPERACAO      = NES_H.IDOPERACAO
    AND OI.FLAGMOVPRODUTOS = 'T'
    AND OI.TIPOMOVIMENTO   IN ('V', 'E')
WHERE EA.IDEMPRESA IN (1, 2, 3)
  AND EA.IDOPERACAO <> 1301
  AND (EA.NUMSEQUENCIAKIT IS NULL OR EA.NUMSEQUENCIAKIT <= 0)
  AND EXISTS (
      SELECT 1 FROM DBA.NOTAS N
      WHERE  N.IDEMPRESA      = EA.IDEMPRESA
        AND  N.IDPLANILHA     = EA.IDPLANILHA
        AND  N.FLAGNOTACANCEL = 'F'
  )
WITH UR
"""

# ─── Estoque Sugestão — snapshot query, NO date parameters ───────────────────
#
# Returns one row per (IDPRODUTO, FABRICANTE) matching cache_campanhas join keys:
#   IDPRODUTO  = PRODUTO_GRADE.IDPRODUTO  (parent product, same as EA.IDPRODUTO)
#   FABRICANTE = PRODUTO.FABRICANTE       (brand text, same as PRD.FABRICANTE)
#
# Aggregates across ALL variant grades (IDSUBPRODUTO) and ALL 3 companies.
# Location 6 excluded (internal transit / reprocessing).
#
# Columns:
#   [0] IDPRODUTO       — product parent ID (TEXT, matches cache_campanhas.IDPRODUTO)
#   [1] FABRICANTE      — brand/manufacturer (TEXT, matches cache_campanhas.FABRICANTE)
#   [2] SALDO_ATUAL     — total physical stock (FLOAT)
#   [3] QTDRESERVA      — total reservations from ESTOQUE_ANALITICO_TMP (FLOAT)
#   [4] SALDO_DISPONIVEL— SALDO_ATUAL - QTDRESERVA (effective available stock) (FLOAT)
#   [5] QTDREPOSICAO    — sum of PRODUTO_COMPRAS.QTDESTMINIMO across variants (FLOAT)
#   [6] DTULT_COMPRA    — most recent purchase date across all variants (DATE or None)
#   [7] VAL_UNITARIO    — unit cost from most recent purchase (FLOAT)
#   [8] QTDPENDENTE     — total qty on open purchase orders not yet received (FLOAT)
#   [9] DESCRICAO       — product description from DBA.PRODUTO.DESCRCOMPRODUTO (TEXT)
SQL_ESTOQUE_SUGESTAO = """
SELECT
    CAST(PG.IDPRODUTO AS VARCHAR(50))                               AS IDPRODUTO,
    CAST(COALESCE(PRD.FABRICANTE, 'SEM FABRICANTE') AS VARCHAR(120)) AS FABRICANTE,
    COALESCE(SUM(ES.SALDO_ATUAL),    0E0)                           AS SALDO_ATUAL,
    COALESCE(SUM(RES.QTDRESERVA),    0E0)                           AS QTDRESERVA,
    (COALESCE(SUM(ES.SALDO_ATUAL),   0E0)
     - COALESCE(SUM(RES.QTDRESERVA), 0E0))                          AS SALDO_DISPONIVEL,
    COALESCE(SUM(PC.QTDREPOSICAO),   0E0)                           AS QTDREPOSICAO,
    MAX(CMP.DTULT_COMPRA)                                           AS DTULT_COMPRA,
    COALESCE(MAX(CMP.VAL_UNITARIO),  0E0)                           AS VAL_UNITARIO,
    COALESCE(SUM(PEN.QTDPENDENTE),   0E0)                           AS QTDPENDENTE,
    CAST(COALESCE(PRD.DESCRCOMPRODUTO, '') AS VARCHAR(255))         AS DESCRICAO
FROM DBA.PRODUTO_GRADE PG
INNER JOIN DBA.PRODUTO PRD
    ON PRD.IDPRODUTO = PG.IDPRODUTO
LEFT JOIN (
    SELECT IDPRODUTO, IDSUBPRODUTO,
           SUM(QTDATUALESTOQUE * 1E0) AS SALDO_ATUAL
    FROM DBA.ESTOQUE_SALDO_ATUAL
    WHERE IDEMPRESA IN (1, 2, 3)
      AND IDLOCALESTOQUE <> 6
      AND QTDATUALESTOQUE BETWEEN -999999999.999 AND 999999999.999
    GROUP BY IDPRODUTO, IDSUBPRODUTO
) ES ON ES.IDPRODUTO = PG.IDPRODUTO AND ES.IDSUBPRODUTO = PG.IDSUBPRODUTO
LEFT JOIN (
    SELECT IDPRODUTO, IDSUBPRODUTO,
           SUM(QTDPRODUTO * 1E0) AS QTDRESERVA
    FROM DBA.ESTOQUE_ANALITICO_TMP
    WHERE IDEMPRESA IN (1, 2, 3)
      AND QTDPRODUTO BETWEEN -999999999.999 AND 999999999.999
    GROUP BY IDPRODUTO, IDSUBPRODUTO
) RES ON RES.IDPRODUTO = PG.IDPRODUTO AND RES.IDSUBPRODUTO = PG.IDSUBPRODUTO
LEFT JOIN (
    SELECT IDPRODUTO, IDSUBPRODUTO,
           SUM(QTDESTMINIMO * 1E0) AS QTDREPOSICAO
    FROM DBA.PRODUTO_COMPRAS
    WHERE IDEMPRESA IN (1, 2, 3)
      AND QTDESTMINIMO > 0
    GROUP BY IDPRODUTO, IDSUBPRODUTO
) PC ON PC.IDPRODUTO = PG.IDPRODUTO AND PC.IDSUBPRODUTO = PG.IDSUBPRODUTO
LEFT JOIN (
    SELECT T.IDPRODUTO, T.IDSUBPRODUTO,
           T.DTMOVIMENTO        AS DTULT_COMPRA,
           T.VALUNITBRUTO * 1E0 AS VAL_UNITARIO
    FROM (
        SELECT EA.IDPRODUTO, EA.IDSUBPRODUTO,
               EA.DTMOVIMENTO, EA.VALUNITBRUTO,
               ROW_NUMBER() OVER (
                   PARTITION BY EA.IDPRODUTO, EA.IDSUBPRODUTO
                   ORDER BY EA.DTMOVIMENTO DESC, EA.IDPLANILHA DESC
               ) AS RN
        FROM DBA.ESTOQUE_ANALITICO EA
        INNER JOIN DBA.OPERACAO_INTERNA OI ON OI.IDOPERACAO = EA.IDOPERACAO
        WHERE OI.TIPOCATEGORIA     = 'C'
          AND OI.TIPOITEMCATEGORIA IN ('C1', 'C2')
          AND OI.IDOPERACAO        <> 801
          AND EA.IDEMPRESA         IN (1, 2, 3)
          AND EA.IDLOCALESTOQUE    <> 6
    ) T WHERE T.RN = 1
) CMP ON CMP.IDPRODUTO = PG.IDPRODUTO AND CMP.IDSUBPRODUTO = PG.IDSUBPRODUTO
LEFT JOIN (
    SELECT PP.IDPRODUTO, PP.IDSUBPRODUTO,
           SUM((PP.QTDSOLICITADA - PP.QTDATENDIDA) * 1E0) AS QTDPENDENTE
    FROM DBA.PEDIDO_COMPRA_PROD PP
    INNER JOIN DBA.PEDIDO_COMPRA PC2
        ON  PP.IDEMPRESA = PC2.IDEMPRESA
        AND PP.IDPEDIDO  = PC2.IDPEDIDO
        AND PC2.IDCLIFOR = PP.IDCLIFOR
    WHERE UPPER(PC2.FLAGCANCELADO)       = 'F'
      AND (PC2.DTVALIDADEPEDIDO >= CURRENT DATE OR PC2.DTVALIDADEPEDIDO IS NULL)
      AND UPPER(PC2.FLAGPEDIDOBLOQUEADO) = 'F'
      AND (PC2.TIPOCATEGORIA IS NULL OR UPPER(PC2.TIPOCATEGORIA) = 'C')
      AND PP.QTDSOLICITADA > PP.QTDATENDIDA
      AND PP.IDEMPRESA IN (1, 2, 3)
    GROUP BY PP.IDPRODUTO, PP.IDSUBPRODUTO
) PEN ON PEN.IDPRODUTO = PG.IDPRODUTO AND PEN.IDSUBPRODUTO = PG.IDSUBPRODUTO
WHERE PG.FLAGINATIVO        = 'F'
  AND PG.FLAGINATIVOCOMPRA  = 'F'
GROUP BY PG.IDPRODUTO, PRD.FABRICANTE, PRD.DESCRCOMPRODUTO
WITH UR
"""

# ─── Tubos & Conexões (filtered subset of vendas by product description) ──────
# Columns: IDVENDEDOR, NOME_VENDEDOR, IDEMPRESA, DT_MOVIMENTO, TOTALVENDA_LINHA, TIPO_PRODUTO
#
# TIPO_PRODUTO classification matches the legacy sync_db2.py logic:
#   - "Tubo"    = product description starts with 'TUBO' (excluding extensions)
#   - "Conexao" = everything else that isn't a tube/accessory
SQL_TUBOS = """
SELECT
    CAST(CASE WHEN COALESCE(EA.IDVENDEDOR, 0) = 0 THEN '0'
         ELSE CAST(EA.IDVENDEDOR AS VARCHAR(50)) END AS VARCHAR(50))   AS IDVENDEDOR,
    CAST(CASE WHEN COALESCE(EA.IDVENDEDOR, 0) = 0 THEN '<SEM VENDEDOR>'
         ELSE COALESCE(VEN.NOME, 'DESCONHECIDO') END AS VARCHAR(120))  AS NOME_VENDEDOR,
    CAST(EA.IDEMPRESA AS INTEGER)                                       AS IDEMPRESA,
    DATE(NES_H.DTMOVIMENTO)                                             AS DT_MOVIMENTO,
    COALESCE(CASE WHEN OI.TIPOMOVIMENTO = 'E'
                  THEN EA.VALTOTLIQUIDO * -1E0
                  ELSE EA.VALTOTLIQUIDO * 1E0 END, 0E0)                AS TOTALVENDA_LINHA,
    CAST(CASE
        WHEN UPPER(COALESCE(PRD.DESCRCOMPRODUTO, '')) LIKE 'TUBO%'
             AND UPPER(COALESCE(PRD.DESCRCOMPRODUTO, '')) NOT LIKE '%EXTENS.%'
        THEN 'Tubo'
        ELSE 'Conexao'
    END AS VARCHAR(20))                                                 AS TIPO_PRODUTO,
    CAST(COALESCE(PRD.FABRICANTE, '') AS VARCHAR(120))                  AS FABRICANTE
FROM DBA.ESTOQUE_ANALITICO EA
LEFT JOIN DBA.CLIENTE_FORNECEDOR VEN ON VEN.IDCLIFOR = EA.IDVENDEDOR
LEFT JOIN DBA.PRODUTO            PRD ON PRD.IDPRODUTO = EA.IDPRODUTO
INNER JOIN (
    SELECT IDEMPRESA, IDPLANILHA, IDOPERACAO,
           MIN(DTMOVIMENTO) AS DTMOVIMENTO
    FROM   DBA.NOTAS_ENTRADA_SAIDA
    WHERE  DTMOVIMENTO >= ?
      AND  DTMOVIMENTO <= ?
      AND  TIPOITEMCATEGORIA NOT IN ('D5', 'D8')
    GROUP BY IDEMPRESA, IDPLANILHA, IDOPERACAO
) NES_H
    ON  NES_H.IDEMPRESA  = EA.IDEMPRESA
    AND NES_H.IDPLANILHA = EA.IDPLANILHA
    AND NES_H.IDOPERACAO = EA.IDOPERACAO
INNER JOIN DBA.OPERACAO_INTERNA OI
    ON  OI.IDOPERACAO      = NES_H.IDOPERACAO
    AND OI.FLAGMOVPRODUTOS = 'T'
    AND OI.TIPOMOVIMENTO   IN ('V', 'E')
WHERE EA.IDEMPRESA IN (1, 2, 3)
  AND EA.IDOPERACAO <> 1301
  AND (EA.NUMSEQUENCIAKIT IS NULL OR EA.NUMSEQUENCIAKIT <= 0)
  AND (
        UPPER(COALESCE(PRD.DESCRCOMPRODUTO, '')) LIKE '%TUBO%'
     OR UPPER(COALESCE(PRD.DESCRCOMPRODUTO, '')) LIKE '%CONEX%'
  )
  AND EXISTS (
      SELECT 1 FROM DBA.NOTAS N
      WHERE  N.IDEMPRESA      = EA.IDEMPRESA
        AND  N.IDPLANILHA     = EA.IDPLANILHA
        AND  N.FLAGNOTACANCEL = 'F'
  )
WITH UR
"""

# ─── Contas a Receber (open receivables snapshot — TRUNCATE+INSERT per run) ───
#
# Source: CONTAS_RECEBER_SALDOS_VIEW (view provided by ERP vendor).
# Columns returned (in order, referenced by index in erp_sync.py):
#   [0]  IDEMPRESA       [1]  IDVENDEDOR       [2]  NOME_VENDEDOR
#   [3]  IDCLIFOR        [4]  NOME_CLIENTE
#   [5]  IDTITULO        [6]  DIGITOTITULO     [7]  SERIENOTA
#   [8]  NUMNOTA         [9]  IDPLANILHA
#   [10] DTMOVIMENTO     [11] DTVENCIMENTO     [12] DTULTIMOPAGAMENTO
#   [13] DIAS_VENCIDO    (DAYS(CURRENT DATE) − DAYS(DTVENCIMENTO), negative = future)
#   [14] VALOR_TITULO    [15] VALOR_SALDO_TITULO  [16] VALOR_LIQUIDO_TITULO
#   [17] VALOR_JUROS_PENDENTE  [18] VALOR_DESCONTO  [19] VALOR_PAGO
#   [20] FORMA_RECEBIMENTO  [21] ORIGEM_MOVIMENTO  [22] OBS_TITULO
#   [23] ENDERECO_COBRANCA  [24] BAIRRO_COBRANCA
#   [25] CIDADE_COBRANCA    [26] UF_COBRANCA
#
# No date parameters — fetches ALL open titles (VALSALDOTITULO > 0).
# Status (VENCIDO / VENCE_HOJE / A_VENCER) computed in Python after fetch.
SQL_CONTAS_RECEBER = """
SELECT
    CAST(CRSV.IDEMPRESA AS INTEGER)                                               AS IDEMPRESA,
    CAST(COALESCE(CF.IDVENDEDOR, 0) AS INTEGER)                                   AS IDVENDEDOR,
    CAST(COALESCE(VEND.NOME, '<SEM VENDEDOR>') AS VARCHAR(120))                   AS NOME_VENDEDOR,
    CAST(CRSV.IDCLIFOR AS INTEGER)                                                AS IDCLIFOR,
    CAST(COALESCE(CF.NOME, CAST(CRSV.IDCLIFOR AS VARCHAR(20))) AS VARCHAR(200))   AS NOME_CLIENTE,
    CAST(CRSV.IDTITULO AS INTEGER)                                                AS IDTITULO,
    CAST(COALESCE(CRSV.DIGITOTITULO, '0') AS VARCHAR(2))                          AS DIGITOTITULO,
    CAST(COALESCE(CRSV.SERIENOTA, '') AS VARCHAR(10))                             AS SERIENOTA,
    CAST(COALESCE(N.NUMNOTA, 0) AS INTEGER)                                       AS NUMNOTA,
    CAST(COALESCE(CRSV.IDPLANILHA, 0) AS INTEGER)                                 AS IDPLANILHA,
    DATE(CRSV.DTMOVIMENTO)                                                        AS DTMOVIMENTO,
    DATE(CRSV.DTVENCIMENTO)                                                       AS DTVENCIMENTO,
    DATE(CRSV.DTULTIMOPAGAMENTO)                                                  AS DTULTIMOPAGAMENTO,
    CAST((DAYS(CURRENT DATE) - DAYS(CRSV.DTVENCIMENTO)) AS INTEGER)              AS DIAS_VENCIDO,
    COALESCE(CRSV.VALTITULO,                    0E0) * 1E0                        AS VALOR_TITULO,
    COALESCE(CRSV.VALSALDOTITULO,               0E0) * 1E0                        AS VALOR_SALDO_TITULO,
    COALESCE(CRSV.VALLIQUIDOTITULO,             0E0) * 1E0                        AS VALOR_LIQUIDO_TITULO,
    COALESCE(CRSV.SUMVALJUROSMORA,              0E0) * 1E0                        AS VALOR_JUROS_PENDENTE,
    COALESCE(CRSV.SUMVALDESCCONCEDIDOTITULO,    0E0) * 1E0                        AS VALOR_DESCONTO,
    (COALESCE(CRSV.VALTITULO, 0E0)
     - COALESCE(CRSV.VALSALDOTITULO, 0E0))     * 1E0                             AS VALOR_PAGO,
    CAST(COALESCE(UPPER(TRIM(FR.DESCRRECEBIMENTO)), '') AS VARCHAR(100))          AS FORMA_RECEBIMENTO,
    CAST(COALESCE(CRSV.ORIGEMMOVIMENTO, '') AS VARCHAR(20))                       AS ORIGEM_MOVIMENTO,
    CAST(COALESCE(CRSV.OBSTITULO, '') AS VARCHAR(500))                            AS OBS_TITULO,
    CAST(COALESCE(NULLIF(CF.ENDERCOBRANCA, ''), CF.ENDERECO, '') AS VARCHAR(200)) AS ENDERECO_COBRANCA,
    CAST(COALESCE(NULLIF(CF.BAIRROCOBRANCA,''), CF.BAIRRO,    '') AS VARCHAR(100)) AS BAIRRO_COBRANCA,
    CAST(COALESCE(CI.DESCRCIDADE, '') AS VARCHAR(100))                             AS CIDADE_COBRANCA,
    CAST(COALESCE(NULLIF(CF.UFCOBRANCA, ''), CF.UFCLIFOR, '') AS VARCHAR(2))      AS UF_COBRANCA,
    CAST('' AS VARCHAR(10))                                                        AS CEP_COBRANCA
FROM DBA.CONTAS_RECEBER_SALDOS_VIEW CRSV
LEFT JOIN DBA.CLIENTE_FORNECEDOR CF
    ON  CF.IDCLIFOR = CRSV.IDCLIFOR
LEFT JOIN DBA.CLIENTE_FORNECEDOR VEND
    ON  VEND.IDCLIFOR = CF.IDVENDEDOR
LEFT JOIN (
    SELECT IDEMPRESA, IDPLANILHA,
           MAX(NUMNOTA) AS NUMNOTA
    FROM DBA.NOTAS
    WHERE FLAGNOTACANCEL = 'F'
    GROUP BY IDEMPRESA, IDPLANILHA
) N
    ON  N.IDEMPRESA  = CRSV.IDEMPRESA
    AND N.IDPLANILHA = CRSV.IDPLANILHA
LEFT JOIN DBA.CIDADES_IBGE CI
    ON  CI.IDCIDADE = COALESCE(NULLIF(CF.IDCIDADECOBRANCA, 0), CF.IDCIDADE)
LEFT JOIN (
    SELECT CR2.IDEMPRESA, CR2.IDPLANILHA, CR2.IDTITULO,
           COALESCE(CR2.DIGITOTITULO, '0')   AS DIGITOTITULO,
           MAX(FP2.DESCRRECEBIMENTO)         AS DESCRRECEBIMENTO
    FROM DBA.CONTAS_RECEBER CR2
    LEFT JOIN DBA.FORMA_PAGREC FP2 ON FP2.IDRECEBIMENTO = CR2.IDRECEBIMENTO
    GROUP BY CR2.IDEMPRESA, CR2.IDPLANILHA, CR2.IDTITULO,
             COALESCE(CR2.DIGITOTITULO, '0')
) FR
    ON  FR.IDEMPRESA    = CRSV.IDEMPRESA
    AND FR.IDPLANILHA   = CRSV.IDPLANILHA
    AND FR.IDTITULO     = CRSV.IDTITULO
    AND FR.DIGITOTITULO = COALESCE(CRSV.DIGITOTITULO, '0')
WHERE CRSV.IDEMPRESA IN (1, 2, 3)
  AND COALESCE(CRSV.VALSALDOTITULO, 0E0) > 0
WITH UR
"""

# ─── Pendentes (open orders — full-replace strategy, aggregated per vendor+empresa) ───
# Columns: IDVENDEDOR[0], NOME_VENDEDOR[1], IDEMPRESA[2], QTD_PEDIDOS[3], VALOR_TOTAL[4]
# Queries ORCAMENTO for orders with pre-nota generated but not yet paid and still valid.
# No date parameters — uses DTVALIDADE >= CURRENT DATE to find all active pending orders.
SQL_PENDENTES = """
WITH OrcamentosPendentes AS (
    SELECT
        O.IDORCAMENTO,
        O.IDEMPRESA
    FROM DBA.ORCAMENTO O
    LEFT JOIN DBA.ORCAMENTO_PRE_NOTA OPN
        ON  OPN.IDORCAMENTO        = O.IDORCAMENTO
        AND OPN.IDEMPRESAORCAMENTO = O.IDEMPRESA
    WHERE
        O.FLAGPRENOTA      = 'T'
        AND O.FLAGPRENOTAPAGA = 'F'
        AND O.FLAGCANCELADO  = 'F'
        AND DATE(COALESCE(O.DTVALIDADE, CURRENT DATE)) >= CURRENT DATE
        AND O.IDEMPRESA IN (1, 3)
        AND COALESCE(OPN.IDPLANILHAPRENOTA, 0) = 0
)
SELECT
    CAST(OP.IDVENDEDOR AS INTEGER)                                      AS IDVENDEDOR,
    CAST(COALESCE(CF.NOME, '<SEM VENDEDOR>') AS VARCHAR(120))          AS NOME_VENDEDOR,
    CAST(OPend.IDEMPRESA AS INTEGER)                                    AS IDEMPRESA,
    CAST(COUNT(DISTINCT OP.IDORCAMENTO) AS INTEGER)                    AS QTD_PEDIDOS,
    CAST(COALESCE(SUM(OP.VALTOTLIQUIDO), 0E0) AS DECIMAL(18,2))       AS VALOR_TOTAL
FROM DBA.ORCAMENTO_PROD OP
INNER JOIN OrcamentosPendentes OPend
    ON  OP.IDORCAMENTO = OPend.IDORCAMENTO
    AND OP.IDEMPRESA   = OPend.IDEMPRESA
LEFT JOIN DBA.CLIENTE_FORNECEDOR CF
    ON CF.IDCLIFOR = OP.IDVENDEDOR
WHERE
    OP.IDVENDEDOR IS NOT NULL
    AND OP.IDVENDEDOR > 0
GROUP BY
    OP.IDVENDEDOR,
    CF.NOME,
    OPend.IDEMPRESA
HAVING COALESCE(SUM(OP.VALTOTLIQUIDO), 0) > 0
ORDER BY VALOR_TOTAL DESC
WITH UR
"""
